In [1]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
Y = np.array(([92], [86], [89]), dtype=float)
X = X/np.amax(X, axis=0)
actual_output = Y / 100
print(X)
print(actual_output)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [2]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

In [3]:
#initialization
epoch = 1000
learning_rate = 0.15
inputlayer_neurons = 2
hiddenlayer_neurons = 3
outputlayer_neurons = 1

# Weight of hidden layer
wh = np.random.uniform(low=-0.05,high=0.05,size=(inputlayer_neurons, hiddenlayer_neurons))#2x3
print(wh)

# Bias of hidden layer
bh = np.random.uniform(low=-0.05,high=0.05,size=(1, hiddenlayer_neurons))

# Weight of output layer
wo = np.random.uniform(low=-0.05,high=0.05, size=(hiddenlayer_neurons, outputlayer_neurons))

# Bias of output layer
bo = np.random.uniform(low=-0.05,high=0.05,size=(1, outputlayer_neurons))

[[ 0.01853081  0.04044836  0.03453377]
 [-0.04123511  0.0130426  -0.01957558]]


In [4]:
# training
for i in range(epoch):
    # Sum of (input * weights in hidden layer) + bias of hidden
    net_h = np.dot(X, wh) + bh

    # Apply Activation Function
    sigma_h = sigmoid(net_h)
    # Input to O/P Layer = (O/P of Hidden Layer * weight of O/P Layer) + bias of O/P layer
    net_o = np.dot(sigma_h, wo) + bo
    # Apply Activation Function
    output = sigmoid(net_o)
    
 #Backpropagation
 # Error at Output layer
    eo = actual_output-output # Error at o/p
    outgrad = derivatives_sigmoid(output)
    d_output = eo* outgrad # Errj=Oj(1-Oj)(Tj-Oj)
    #print("the d_output is",d_output)

# Error at Hidden later
    eh = d_output.dot(wo.T) # .T means transpose
    hiddengrad = derivatives_sigmoid(sigma_h) # How much hidden layer wts contributed to error
    d_hidden = eh * hiddengrad
    wo += sigma_h.T.dot(d_output) *learning_rate # Dotproduct of nextlayererror and currentlayerop
    wh += X.T.dot(d_hidden) *learning_rate
    
    sum_error = 0
    
    for j in range(len(actual_output)):
        print(output[j],actual_output[j] )
        sum_error+=((output[j] - actual_output[j])**2)
    sum_error /=2
    
    print(f'Epoch {i} error {sum_error}')



[0.4965925] [0.92]
[0.49658484] [0.86]
[0.49660644] [0.89]
Epoch 0 error [0.23305149]
[0.50483224] [0.92]
[0.50480977] [0.86]
[0.50491076] [0.89]
Epoch 1 error [0.22340905]
[0.51289984] [0.92]
[0.51286132] [0.86]
[0.51304143] [0.89]
Epoch 2 error [0.21416678]
[0.52079494] [0.92]
[0.5207377] [0.86]
[0.52099794] [0.89]
Epoch 3 error [0.20531305]
[0.52851768] [0.92]
[0.52843782] [0.86]
[0.5287803] [0.89]
Epoch 4 error [0.19683578]
[0.53606863] [0.92]
[0.53596123] [0.86]
[0.53638896] [0.89]
Epoch 5 error [0.18872259]
[0.54344877] [0.92]
[0.54330806] [0.86]
[0.54382483] [0.89]
Epoch 6 error [0.18096093]
[0.5506594] [0.92]
[0.55047895] [0.86]
[0.55108915] [0.89]
Epoch 7 error [0.17353816]
[0.55770216] [0.92]
[0.55747503] [0.86]
[0.55818349] [0.89]
Epoch 8 error [0.16644164]
[0.56457892] [0.92]
[0.56429781] [0.86]
[0.56510972] [0.89]
Epoch 9 error [0.15965881]
[0.57129182] [0.92]
[0.5709492] [0.86]
[0.57186994] [0.89]
Epoch 10 error [0.15317724]
[0.57784318] [0.92]
[0.57743141] [0.86]
[0.5784

In [5]:
print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(actual_output))
print("Predicted Output: \n" ,output)

Normalized Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89596775]
 [0.87793846]
 [0.89595032]]
