In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()
data = iris.data
target = iris.target

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.20, random_state=25)
print(iris.data.shape)
print('Training Set', len(data_train))
print('Test Set', len(data_test))

(150, 4)
Training Set 120
Test Set 30


In [8]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=3)
KNN.fit(data_train,target_train)
target_pred = KNN.predict(data_test)
print(target_pred)

[0 2 2 1 2 1 2 0 1 1 0 0 0 2 0 1 2 2 1 1 1 1 1 0 0 2 1 2 2 0]


In [9]:
from sklearn import metrics
print("Accuracy = ", metrics.accuracy_score(target_pred, target_test))
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(target_test,target_pred))
print(classification_report(target_test,target_pred))

Accuracy =  0.9333333333333333
[[ 9  0  0]
 [ 0 11  2]
 [ 0  0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.85      0.92        13
           2       0.80      1.00      0.89         8

    accuracy                           0.93        30
   macro avg       0.93      0.95      0.94        30
weighted avg       0.95      0.93      0.93        30



In [10]:
predicted=KNN.predict(data_test)
predictedTargetArray=[iris.target_names[i] for i in predicted]
actualTargetArray=[iris.target_names[i] for i in target_test]
print("\t Predicted","\t\tActual","\t\t\tAnswer")
for itr in range(0,len(predictedTargetArray)):
    print(itr,":",predictedTargetArray[itr],"\t\t",actualTargetArray[itr],"\t\t",end='\t')
    if(predictedTargetArray[itr]==actualTargetArray[itr]):
        print("Yes")
    else:
        print("No")

	 Predicted 		Actual 			Answer
0 : setosa 		 setosa 			Yes
1 : virginica 		 versicolor 			No
2 : virginica 		 versicolor 			No
3 : versicolor 		 versicolor 			Yes
4 : virginica 		 virginica 			Yes
5 : versicolor 		 versicolor 			Yes
6 : virginica 		 virginica 			Yes
7 : setosa 		 setosa 			Yes
8 : versicolor 		 versicolor 			Yes
9 : versicolor 		 versicolor 			Yes
10 : setosa 		 setosa 			Yes
11 : setosa 		 setosa 			Yes
12 : setosa 		 setosa 			Yes
13 : virginica 		 virginica 			Yes
14 : setosa 		 setosa 			Yes
15 : versicolor 		 versicolor 			Yes
16 : virginica 		 virginica 			Yes
17 : virginica 		 virginica 			Yes
18 : versicolor 		 versicolor 			Yes
19 : versicolor 		 versicolor 			Yes
20 : versicolor 		 versicolor 			Yes
21 : versicolor 		 versicolor 			Yes
22 : versicolor 		 versicolor 			Yes
23 : setosa 		 setosa 			Yes
24 : setosa 		 setosa 			Yes
25 : virginica 		 virginica 			Yes
26 : versicolor 		 versicolor 			Yes
27 : virginica 		 virginica 			Yes
28 : virginica 		 virgini